name: Databricks CD

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do projeto corrente
        uses: actions/checkout@v3
      
      - name: Configurando o python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Get the modified file in "resource"
        run: |
            arquivo_modificado=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^resource/")
            echo "::set-output name=arquivo_modificado::${arquivo_modificado}"
        id: get_arquivo_modificado
    
    
      - name: Deploy dos arquivos a partir do repositorio git no Workspace Databricks de HML
        env:
          DATALAKE_DATABRICKS_CLIENT_ID: ${{ secrets.DATALAKE_DATABRICKS_CLIENT_ID }}
          DATALAKE_DATABRICKS_CLIENT_SECRET: ${{ secrets.DATALAKE_DATABRICKS_CLIENT_SECRET }}
          DATALAKE_DATABRICKS_WORKSPACE_URL: ${{ vars.DATALAKE_DATABRICKS_WORKSPACE_URL_HML }}
          DATALAKE_DATABRICKS_GIT_USERNAME: ${{ vars.DATALAKE_DATABRICKS_GIT_USERNAME }}
          DATALAKE_DATABRICKS_GIT_TOKEN: ${{ secrets.DATALAKE_DATABRICKS_GIT_TOKEN }}
          DATALAKE_DATABRICKS_REPO_USER: ${{ vars.DATALAKE_DATABRICKS_REPO_USER }}
          DATALAKE_DATABRICKS_REPO_URL: ${{ github.server_url }}/${{ github.repository }}.git
          DATALAKE_DATABRICKS_GIT_BRANCH_REF: master
        run: |
          echo "repository variable : ${{ secrets.DATALAKE_DATABRICKS_CLIENT_ID }}"
          echo "organization variable : ${{ secrets.DATALAKE_DATABRICKS_CLIENT_SECRET }}"
          echo "DATALAKE_DATABRICKS_WORKSPACE_URL_HML : ${{ vars.DATALAKE_DATABRICKS_WORKSPACE_URL_HML }}"
          echo "variable from shell environment : $env_var"



          