name: Get Changed File

on: [push]

jobs:
  get_changed_file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the list of changed files
        id: changed_files
        run: |
          echo "::set-output name=changed_files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})"
        shell: bash

      - name: Print changed files
        run: |
          changed_files="${{ steps.changed_files.outputs.changed_files }}"
          IFS=$'\n' read -rd '' -a files <<< "$changed_files"
          for file in "${files[@]}"; do
            echo "Changed file: $file"
            # Use $file in your GitHub Action workflow
          done