name: Python CI

on:
  push:
    branches: [ "main", "master" ]
    paths:
      - 'toolkit/file.py'
      - 'resources/**'  # Apenas alterações na pasta "resource" acionarão o workflow..,

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: List Modified Files
      id: git-changes
      run: |
          git diff --name-status ${{ github.event.before }} ${{ github.sha }} > changed-files.txt
          cat changed-files.txt


    # - name: Install dependencies
    #   run: |
    #     pip install -r requirements.txt

    # - name: Get the modified file in "resources"
    #   run: |
    #     arquivo_modificado=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^resources/")
    #     echo "::set-output name=arquivo_modificado::${arquivo_modificado}"
    #   id: get_arquivo_modificado

    # - name: Run Python script with modified file
    #   run: |
    #     python toolkit/file.py "${{ steps.get_arquivo_modificado.outputs.arquivo_modificado }}"
        
#ssad        555
