name: Python CI

on:
  push:
    branches: [ "main", "master" ]
    #paths:
    #  - 'toolkit/file.py'
    #  - 'resources/**'  # Apenas alterações na pasta "resource" acionarão o workflow..,

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: List Modified Files
      id: git-changes
      run: |
          git diff --name-status @{u} ${{ github.sha }} > changed-files.txt
          cat changed-files.txt