# Documentation:
# This workflow is triggered on push to the "main" or "master" branches and when there are changes in the "resources" folder.
name: Python CI

on:
  push:
    branches:
      - main
      - master
    #paths:
     # - 'resources/**'  # Only changes in the "resources" folder will trigger the workflow.

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Clona o repositório com histórico completo      

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Get the last commit hash
      id: last_commit
      run: |
          last_commit_hash=$(/usr/bin/git log -1 --format='%H')
          echo "::set-output name=last_commit_hash::$last_commit_hash"
      shell: bash

    - name: Get the list of changed files
      id: changed_files
      run: |
          changed_files=$(/usr/bin/git diff --name-only ${{ steps.last_commit.outputs.last_commit_hash }})
          echo "::set-output name=changed_files::$changed_files"
      shell: bash

    - name: Print changed files
      run: |
          changed_files="${{ steps.changed_files.outputs.changed_files }}"
          IFS=$'\n' read -rd '' -a files <<< "$changed_files"
          for file in "${files[@]}"; do
            echo "Changed file: $file"
            # Use $file in your GitHub Action workflow
          done


