name: Python CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use checkout@v4
      with:
        fetch-depth: 0  # Clone the repository with full history

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: List Modified Files
      id: git-changes
      run: |
            # Get the list of modified files
            if [ "${{ github.event.head_commit.id }}" != "${{ github.event.before }}" ]; then
              git diff --name-status ${{ github.event.before }} ${{ github.event.head_commit.id }} | awk '{print $2}' > changed-files.txt
            else
              echo "No changes in this push."
            fi
  
            # Display the content of changed-files.txt for verification
            cat changed-files.txt
  
    - name: Run Python Script with Modified Files
      run: |
            # Process each file from the list
            while IFS= read -r filename
            do
                python3 toolkit/file.py --filename "$filename"
            done < changed-files.txt
 
  
  
  
  
  