name: Databricks CD

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout do projeto corrente
        uses: actions/checkout@v3
      
      - name: Configurando o python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x


      - name: Run Makefile - Find Changed Files
        run: make find_changed_files
        id: find_changed_files
    
      - name: Run Makefile - Install Dependencies
        run: make install
    
      - name: Run Makefile - Run Tests
        run: make test