name: Python CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Clone the repository with full history

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Install Dependencies
      run: make install
      # Description: Install project dependencies by running the Makefile

    - name: Run Tests
      run: make test
      # Description: Execute project tests using the Makefile

    - name: List Modified Files
      run: make list-modified-files
      # Description: List modified files in the repository using the Makefile

    - name: Deploy
      run: make deploy
      # Description: Execute the application deployment process using the Makefile
