name: CI/CD Workflow

on:
  push:
    paths:
      - 'resources/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Set JOB_PARAMETER
      run: echo "::set-env name=JOB_PARAMETER::valor_do_parametro"

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Run Tests
      run: make test

    - name: Run Deployment
      run: make deploy