name: Python CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Use checkout@v4
      with:
        fetch-depth: 0  # Clone the repository with full history

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.0

    - name: Run Makefile - Install Dependencies
      run: make install
  
    - name: Run Makefile - Run Tests
      run: make test

    - name: Run Makefile - Deploy
      run: make list-modified-files    

    - name: Run Makefile - Deploy
      run: make run-python-script
  
  
  
  
  